{% set name = "lux-api" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lux-api-{{ version }}.tar.gz
  sha256: af451e85d263c03fd596251373ff6e34d04e0c0609f2410c830114b84b102613

build:
  skip: true # [(win and py2k) or (python_impl == 'pypy')]
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.1
  run:
    - python >=3.7.1
    - scipy >=1.3.3
    - altair >=4.0.0
    - numpy >=1.19.5
    - pandas >=1.2.0
    - scikit-learn >=0.22
    - lux-widget >=0.1.4
    - matplotlib-base >=3.0.0
    - us
    - iso3166

test:
  imports:
    - lux
    - lux._config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lux-org/lux
  summary: A Python API for Intelligent Data Discovery
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dorisjlee
