{% set name = "lux-api" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lux-api-{{ version }}.tar.gz
  sha256: af451e85d263c03fd596251373ff6e34d04e0c0609f2410c830114b84b102613

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - scipy
    - pandas >=1.2
    - scikit-learn
    - lux-widget >=0.1.4
    - altair
    - numpy
    - matplotlib-base
    - jellyfish
    - us
    - iso3166
test:
  imports:
    - lux
    - lux._config
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lux-org/lux
  summary: A Python API for Intelligent Data Discovery
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dorisjlee
